# Generated by Django 3.2.16 on 2022-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='reason',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
