# Generated by Django 3.2.16 on 2023-03-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20230308_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
    ]
