# Generated by Django 3.2.16 on 2023-03-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
    ]
