# Generated by Django 3.2.16 on 2023-03-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_rename_author_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
    ]
